services:
  - type: web
    name: claimcheck
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_CX_ID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
